In [9]:
import numpy as np

# Example data
len_data = 4000
bufferlen = 4
framesize = 257

array1 = np.random.rand(len_data, bufferlen, framesize)
array2 = np.random.rand(len_data, framesize)

In [12]:
import torch

# Concatenate arrays
reshaped_array1 = array1.reshape(len_data, -1)
combined_array = np.concatenate([reshaped_array1, array2], axis=1)

# Convert to PyTorch tensor
combined_tensor = torch.tensor(combined_array)

# Split the tensor back into two tensors
tensor1 = combined_tensor[:, :bufferlen * framesize].reshape(len_data, bufferlen, framesize)
tensor2 = combined_tensor[:, bufferlen * framesize:]

print(array1.shape)
print(array2.shape)
print(combined_array.shape)
print(tensor1.shape)
print(tensor2.shape)


# Display the original arrays, combined tensor, and separated tensors
print("Original array1:")
print(array1)
print("\nOriginal array2:")
print(array2)

print("\nCombined tensor:")
print(combined_tensor)

print("\nSeparated tensor1:")
print(tensor1)
print("\nSeparated tensor2:")
print(tensor2)

(4000, 4, 257)
(4000, 257)
(4000, 1285)
torch.Size([4000, 4, 257])
torch.Size([4000, 257])
Original array1:
[[[0.7928131  0.87217769 0.47213508 ... 0.52465682 0.47560087 0.81129372]
  [0.89546906 0.65056677 0.0703766  ... 0.52935601 0.36517016 0.84676727]
  [0.78483195 0.42367364 0.98519362 ... 0.48997061 0.00792857 0.40131445]
  [0.25116497 0.96813858 0.47099337 ... 0.97461779 0.18936619 0.03669519]]

 [[0.26458842 0.58582114 0.70070103 ... 0.42901354 0.47806788 0.85728647]
  [0.36205999 0.47434032 0.52794848 ... 0.04823638 0.82210381 0.24155752]
  [0.29283846 0.86105299 0.44033512 ... 0.9699399  0.65254226 0.5485455 ]
  [0.59577546 0.04409469 0.15768091 ... 0.95421344 0.78616282 0.38036899]]

 [[0.82325937 0.34079686 0.61790841 ... 0.68886186 0.64462207 0.69749898]
  [0.66159789 0.87842915 0.16878963 ... 0.88509525 0.68890646 0.69681178]
  [0.72591095 0.31527445 0.21124028 ... 0.44970915 0.09929867 0.59190854]
  [0.55412564 0.3707953  0.42412373 ... 0.69524609 0.13274476 0.46457839]]

In [14]:
combined_tensor = combined_tensor[:200]

tensor1 = combined_tensor[:, :bufferlen * framesize].reshape(200, bufferlen, framesize)
tensor2 = combined_tensor[:, bufferlen * framesize:]

print(combined_tensor.shape)
print(tensor1.shape)
print(tensor2.shape)


torch.Size([200, 1285])
torch.Size([200, 4, 257])
torch.Size([200, 257])
